# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ura Design
email: hello@ura.design
description: > # this means to ignore newlines until "baseurl:"
  Ura is a digital studio which focuses on visual communication solutions tailored for Open Source and Internet Freedom projects.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: uracreative
github_username:  uracreative

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/older:num"
